name: Go Paperless
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353430'
    - '#767772'
    - '#f7f6f2'
    - '#a3a29e'
    - '#aa4f32'
  brandStrength: 1
  lightness: 0.00275399093516171
  saturation: 0.6433779343497008
  rhythmicContrast: 0.2720668560359627
purpose: []
