name: Go Paperless
favicon: null
layout_spectrum: 0.4934432697482407
typography_spectrum: 0.4725828352384269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.29553168662823737
  lightness: 0.00275399093516171
  saturation: 0.6433779343497008
  rhythmicContrast: 0.2720668560359627
purpose: []
