name: Go Paperless
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2003d'
    - '#9cc800'
    - '#151515'
    - '#eb5b80'
    - '#727272'
  brandStrength: 0.5625
  lightness: 0.00275399093516171
  saturation: 0.6433779343497008
  rhythmicContrast: 0.2720668560359627
purpose: []
